name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:

jobs:
  deploy-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create build dir
        run: mkdir -p build
      - name: Generate msteams.lsrules
        run: "./gen-msteams > build/msteams.lsrules"
      - name: Check the time
        id: time
        run: echo "now=$(date --rfc-3339=seconds)" >> $GITHUB_OUTPUT
      - name: Publish msteams.lsrules
        uses: popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/maxim/885e395b7d6cd2991790c0f3167326ee
          gist_title: msteams.lsrules
          gist_description: Little Snitch rules for Microsoft Teams, updated at ${{ steps.time.outputs.now }}.
          github_file: ./build/msteams.lsrules
